# Problem 1 - Tensors and Automatic Differentiation

In [4]:
import torch
import numpy as np

## 1a) Tensors

In [15]:
# Creating a tensor from a list

a_data = [1.0, 2.0, 3.0, 4.0, 5.0]

a = torch.tensor(a_data)
a

tensor([1., 2., 3., 4., 5.])

In [16]:
# Creating a tensor from a numpy array

b_data = np.ones((3, 3))

b = torch.tensor(b_data)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
# Reshaping a tensor follows the same syntax as numpy arrays

a = a.reshape(5,1)
a

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

In [ ]:
# Element-wise operations also follow the same syntax as numpy

# Computing the element-wise square of elements in 'a'
a ** 2

tensor([ 1.,  4.,  9., 16., 25.])

In [ ]:
# As do matrix operations

# Compute the dot product of matrix 'b' with itself
b @ b

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)

## 1b) Autograd

The autograd feature computes gradients of tensors automatically.

In [ ]:
def f(x):
    y= x**2 + 3*x + 1
    return y 

 Analytically, we can easily take the first derivative with respect to x. Then:

$$
\frac{dy}{dx} = 2x + 3
$$

At $x=2$, this leads to a gradient equal to $7$.

Autograd does this automatically:

In [28]:
# Create a tensor, and explicitly require the gradient to be computed
x = torch.tensor([2.0], requires_grad=True)

# Transfrom x by the function
y = f(x)

# Call this to back out the gradient
y.backward()

print("f'(x) =", x.grad.item())

f'(x) = 7.0


## 1c) Multivariate functions

In [30]:
def g(x, y):
    z = x**2 * y + y**3
    return z

Analytically, we can take first order partial derivatives:

$$
\frac{\delta z}{\delta x} = 2xy
$$

$$
\frac{\delta z}{\delta y} = x^{2} + 3y^{2}
$$

When $x=1$, $y=2$:

$$
\frac{\delta z}{\delta x} = 4
$$

$$
\frac{\delta z}{\delta y} = 13
$$

And again, PyTorch does this automatically using autograd:

In [32]:
# Create tensors
x = torch.tensor([1.0], requires_grad=True)
y = torch.tensor([2.0], requires_grad=True)

# Apply function
z = g(x,y)

# Use .backward() to compute partial derivatives
z.backward()

print("dz/dx =", x.grad.item())
print("dz/dy =", y.grad.item()) 

dz/dx = 4.0
dz/dy = 13.0
